language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install: "pip install -r requirements.txt"
script: py.test --cov dsq --cov-report term-missing --cov-fail-under=100
services:
  - redis-server
cache:
  - pip
