language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.11"
  - "pypy"
install: "pip install -r requirements.txt"
script: py.test --cov dsq --cov-report term-missing --cov-fail-under=100
services:
  - redis-server
cache:
  - pip
